---

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  sha: v1.3.0
  hooks:
    - id: trailing-whitespace
      exclude: README.md
    - id: end-of-file-fixer
      exclude: README.md$
    - id: check-json
    - id: check-xml
    - id: check-ast
    - id: check-added-large-files
      args: [ '--maxkb=50' ]
    - id: check-merge-conflict
    - id: detect-private-key
    - id: mixed-line-ending
      args: [ '--fix=lf' ]


- repo: https://github.com/Kintyre/ksconf
  sha: v0.5.1
  hooks:
    - id: ksconf-check
#    - id: ksconf-sort
